### ISSUE TITLE
[lio_sam_mapOptmization-4] process has died [pid 33731, exit code -11

### ISSUE THREAD

**Issue by vedant-banerjee** [Gaochao-hit/LIO-SAM-extending1#3]
![Screenshot from 2022-11-18 17-19-28](https://user-images.githubusercontent.com/67970392/202701176-7b6efbda-e289-4762-b75c-37c686b468dc.png)

I am encountering this error when i try to run my launch file, any solutions?

**Comment by vedant-banerjee** [comment]
@Gaochao-hit

**Comment by ustczhs** [comment]
I met this problem before and here's a solution, rebuild and reinstall your gtsam(version: 4.0.2) with "cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..". Enjoy~

**Comment by vedant-banerjee** [comment]
Tried this way but it still fails
